name: Default Workflow
on: [workflow_dispatch]
jobs:
    Run-Default:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was automatically triggered by a ${{ github.event_name }} event. This job is now running on a ${{ runner.os }} server. The name of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."

            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}

            - name: Super Linter
              uses: super-linter/super-linter@v7.2.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: echo "This job's status is ${{ job.status }}."