name: Voting Workflow
on: 
    push:
        branches:
            - 'main'
        paths:
            - 'voting/**'
    pull_request:
        branches:
            - 'main'
        paths:
            - 'voting/**'
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./voting

        steps:
            - uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                java-version: '19'
                distribution: 'temurin'

            - name: Build with Maven
              run: mvn -B package --file pom.xml -DskipTests

            - name: Test
              run: mvn test