name: Voting Workflow
on: 
    push:
        branches:
            - 'main'
        paths:
            - 'voting/**'
    pull_request:
        branches:
            - 'main'
        paths:
            - 'voting/**'
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./voting

        steps:
            - uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                java-version: '19'
                distribution: 'temurin'

            - name: Build with Maven
              run: mvn -B package --file pom.xml -DskipTests

            - name: Test
              run: mvn test

    package:
        needs: build-and-test
        if: github.event_name != 'pull_request'
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./voting

        steps:
          - uses: actions/checkout@v4

          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: ./voting
              push: true
              tags: ${{ vars.DOCKERHUB_USERNAME }}/craftista-voting:latest